### ISSUE TITLE
Leaderboard appears to be frozen again

### ISSUE THREAD

**Issue by misanthropicscott** [andrensegura/spiral-number-game#1]
Hi Bibbleskit,

The leaderboard appears to be stuck again. I'm not seeing changes to scores or pebbles for at least myself and Sinjury.

Thanks,
MisanthropicScott

**Comment by bibbleskit** [comment]
The leaderboard and user pages refresh every 5 minutes. Does it look better to you now?

**Comment by misanthropicscott** [comment]
I see my pebbles at 260,932 and my score at 37,732. They have been the same for several days.

Want to wait an hour 'til 3AM NYC time or midnight CA time when it used to update?

**Comment by misanthropicscott** [comment]
Seems to be fixed now. Sinjury is kicking my ass, but that's fine.

**Comment by bibbleskit** [comment]
Closed. The issue was as follows:

1. Users' daily gains are stored in a separate database field.
2. When pebbles distributions are calculated, this number goes up.
3. When score is calculated, this number is reduced to 0.
4. Score and pebble calculation were set to run daily at the same time.
5. Score calculation is much much faster, meaning it reset the daily pebble gain to 0 before pebbles could be calculated.
6. Offset for calculations added so scores are updated later.
